/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_android_ImageBlur */

#ifndef _Included_com_example_android_ImageBlur
#define _Included_com_example_android_ImageBlur
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_android_ImageBlur
 * Method:    blurIntArray
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_com_example_android_ImageBlur_blurIntArray
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

/*
 * Class:     com_example_android_ImageBlur
 * Method:    blurBitMap
 * Signature: (Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_example_android_ImageBlur_blurBitMap
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
